backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dhuzzgcgt
    api_key: 853134381385575

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "kegiatan"
    label: "Kegiatan"
    folder: "contents/kegiatan"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "/kegiatan/{{slug}}"
    sort: "date:desc"
    fields:
      - { label: "Judul", name: "title", widget: "string", required: true }
      - {
          label: "Tanggal",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          date_format: "DD MMMM YYYY",
          time_format: false,
          required: true,
        }
      - { label: "Gambar", name: "image", widget: "image", required: true }
      - { label: "Isi", name: "body", widget: "markdown", required: true }

  - name: "pengurus"
    label: "Pengurus"
    files:
      - file: "contents/pengurus/ketua.md"
        label: "Ketua"
        name: "ketua"
        fields:
          - { label: "Nama", name: "nama", widget: "string", required: true }
          - {
              label: "Posisi",
              name: "posisi",
              widget: "string",
              required: true,
            }
          - { label: "Foto", name: "foto", widget: "image", required: true }
      - file: "contents/pengurus/sekretaris.md"
        label: "Sekretaris"
        name: "sekretaris"
        fields:
          - { label: "Nama", name: "nama", widget: "string", required: true }
          - {
              label: "Posisi",
              name: "posisi",
              widget: "string",
              required: true,
            }
          - { label: "Foto", name: "foto", widget: "image", required: true }
      - file: "contents/pengurus/bendahara.md"
        label: "Bendahara"
        name: "bendahara"
        fields:
          - { label: "Nama", name: "nama", widget: "string", required: true }
          - {
              label: "Posisi",
              name: "posisi",
              widget: "string",
              required: true,
            }
          - { label: "Foto", name: "foto", widget: "image", required: true }
  - name: "produk"
    label: "Produk"
    folder: "contents/produk"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama Produk", name: "name", widget: "string", required: true }
      - { label: "Gambar", name: "image", widget: "image", required: true }
      - { label: "Produk Unggulan?", name: "unggulan", widget: "boolean", default: false }
      
